"""new_task

Revision ID: 39ea022ccd16
Revises: e98b27e3a704
Create Date: 2025-03-28 12:13:20.413709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ea022ccd16'
down_revision: Union[str, None] = 'e98b27e3a704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_column('userprofile', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'user_id')
    # ### end Alembic commands ###
