"""new-model-user

Revision ID: 8338f4a1eda8
Revises: dd1c0bd2cffa
Create Date: 2025-04-02 21:46:23.863461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8338f4a1eda8'
down_revision: Union[str, None] = 'dd1c0bd2cffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('userprofile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userprofile', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('userprofile', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
