"""extend-user-profile

Revision ID: dd1c0bd2cffa
Revises: 39ea022ccd16
Create Date: 2025-04-01 10:41:28.272074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd1c0bd2cffa'
down_revision: Union[str, None] = '39ea022ccd16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('email', sa.String(), nullable=True))
    op.add_column('userprofile', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userprofile', 'name')
    op.drop_column('userprofile', 'email')
    op.drop_column('userprofile', 'google_access_token')
    # ### end Alembic commands ###
